### ISSUE TITLE
这个报错是啥意思？

### ISSUE THREAD

**Issue by linword** [KarisAya/nonebot_plugin_game_collection#1]
```
08-17 15:18:37 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_game_collection, type=message, priority=5, temp=False>
08-17 15:18:37 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_game_collection, type=message, priority=5, temp=False> running complete
08-17 15:18:37 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_game_collection, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "/root/venv/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/venv/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/root/venv/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/root/venv/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/root/venv/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/root/venv/lib/python3.9/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/root/venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/venv/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/venv/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/venv/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/venv/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/root/venv/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/root/venv/lib/python3.9/site-packages/nonebot_plugin_game_collection/__init__.py", line 647, in _
    msg = single_manager.gacha(event)
  File "/root/venv/lib/python3.9/site-packages/nonebot_plugin_game_collection/data_source.py", line 1447, in gacha
    russian_manager._player_data[group_id][user_id]["props"].setdefault("四叶草标记",0)
KeyError: 'props'

```

**Comment by KarisAya** [comment]
在十连之前没有签到吗

**Comment by linword** [comment]
> 在十连之前没有签到吗

有签到，之前俄罗斯转盘的数据有1343个金币，需要把之前的data删了嘛？

**Comment by linword** [comment]
emmm，确实是之前的俄罗斯转盘插件的data.json问题，里面没有你这个插件的某些属性值，我删了重新生成后没问题了，辛苦了
