### ISSUE TITLE
发起挑战没有人接受不能创建赛马

### ISSUE THREAD

**Issue by laiyoi** [KarisAya/nonebot_plugin_game_collection#29]
```
08-18 13:39:13 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_game_collection) failed.
Traceback (most recent call last):
  File "E:\nb\test\bot.py", line 19, in <module>
    nonebot.run()
  File "E:\anaconda\envs\nb\lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "E:\anaconda\envs\nb\lib\site-packages\nonebot\drivers\fastapi.py", line 199, in run
    uvicorn.run(
  File "E:\anaconda\envs\nb\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "E:\anaconda\envs\nb\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "E:\anaconda\envs\nb\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\anaconda\envs\nb\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "E:\anaconda\envs\nb\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "E:\anaconda\envs\nb\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "E:\anaconda\envs\nb\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "E:\anaconda\envs\nb\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\anaconda\envs\nb\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "E:\anaconda\envs\nb\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\anaconda\envs\nb\lib\site-packages\nonebot\internal\matcher\matcher.py", line 759, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\anaconda\envs\nb\lib\site-packages\nonebot\internal\matcher\matcher.py", line 734, in simple_run
    await handler(
  File "E:\anaconda\envs\nb\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\anaconda\envs\nb\lib\site-packages\nonebot_plugin_game_collection\__init__.py", line 390, in _
    msg = game.creat(event,**kwargs)
  File "E:\anaconda\envs\nb\lib\site-packages\nonebot_plugin_game_collection\Game.py", line 1628, in creat
    flag, msg = cls.start(event, **kwargs)
  File "E:\anaconda\envs\nb\lib\site-packages\nonebot_plugin_game_collection\Game.py", line 1640, in start
    if msg := game.create_check():
AttributeError: 'Russian' object has no attribute 'create_check'
```
除了被邀请挑战的人接收挑战或重启bot无法解决，没有提示，即使邀请过期也不行

**Comment by KarisAya** [comment]
使用游戏重置指令

**Comment by KarisAya** [comment]
更新了提示
