### ISSUE TITLE
加载时报错

### ISSUE THREAD

**Issue by YUANJUN233** [KarisAya/nonebot_plugin_game_collection#30]
08-26 22:59:49 [ERROR] nonebot | Failed to import "nonebot_plugin_game_collection"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot_plugin_game_collection/__init__.py", line 31, in <module>
    from . import Manager
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot_plugin_game_collection/Manager.py", line 15, in <module>
    from .utils.chart import gini_coef, default_BG
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot_plugin_game_collection/utils/chart.py", line 20, in <module>
    from ..config import BG_image,fontname,fallback_fonts
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot_plugin_game_collection/config.py", line 88, in <module>
    config = Config.parse_obj(global_config.dict())
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Config
game_fallback_fonts
  value is not a valid list (type=type_error.list)

求大佬帮助捏

**Comment by KarisAya** [comment]
加载配置出错，env里game_fallback_fonts写的什么？

**Comment by YUANJUN233** [comment]
# 默认备用字体
game_fallback_fonts = [
    "Arial",
    "Tahoma",
    "Microsoft YaHei",
    "Segoe UI",
    "Segoe UI Emoji",
    "Segoe UI Symbol",
    "Helvetica Neue",
    "PingFang SC",
    "Hiragino Sans GB",
    "Source Han Sans SC",
    "Noto Sans SC",
    "Noto Sans CJK JP",
    "WenQuanYi Micro Hei",
    "Apple Color Emoji",
    "Noto Color Emoji",
    ]

就还是默认的这些

**Comment by KarisAya** [comment]
> # 默认备用字体
> game_fallback_fonts = [ "Arial", "Tahoma", "Microsoft YaHei", "Segoe UI", "Segoe UI Emoji", "Segoe UI Symbol", "Helvetica Neue", "PingFang SC", "Hiragino Sans GB", "Source Han Sans SC", "Noto Sans SC", "Noto Sans CJK JP", "WenQuanYi Micro Hei", "Apple Color Emoji", "Noto Color Emoji", ]
> 
> 就还是默认的这些

把这个删了

**Comment by YUANJUN233** [comment]
Failed to import "nonebot_plugin_game_collection"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot_plugin_game_collection/__init__.py", line 31, in <module>
    from . import Manager
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot_plugin_game_collection/Manager.py", line 15, in <module>
    from .utils.chart import gini_coef, default_BG
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/nonebot_plugin_game_collection/utils/chart.py", line 29, in <module>
    font_big = ImageFont.truetype(font = fontname, size = 60, encoding = "utf-8")
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 791, in truetype
    return freetype(font)
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 788, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/Users/mac/nb/jam233/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 226, in __init__
    self.font = core.getfont(
OSError: cannot open resource
貌似还是不大行
