### ISSUE TITLE
加载时报错

### ISSUE THREAD

**Issue by RICHQAQ** [KarisAya/nonebot_plugin_game_collection#31]
卸载插件重装已经是这个问题

10-19 21:22:19 [ERROR] nonebot | Failed to import "nonebot_plugin_game_collection"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\bot\gpt3\.venv\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\bot\gpt3\.venv\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\bot\gpt3\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\bot\gpt3\.venv\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\bot\gpt3\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\bot\gpt3\.venv\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\bot\gpt3\.venv\lib\site-packages\nonebot_plugin_game_collection\__init__.py", line 31, in <module>
    from . import Manager
  File "C:\bot\gpt3\.venv\lib\site-packages\nonebot_plugin_game_collection\Manager.py", line 15, in <module>
    from .utils.chart import gini_coef, default_BG
  File "C:\bot\gpt3\.venv\lib\site-packages\nonebot_plugin_game_collection\utils\chart.py", line 8, in <module>
    import matplotlib.pyplot as plt
  File "C:\bot\gpt3\.venv\lib\site-packages\matplotlib\__init__.py", line 286, in <module>
    _check_versions()
  File "C:\bot\gpt3\.venv\lib\site-packages\matplotlib\__init__.py", line 280, in _check_versions
    module = importlib.import_module(modname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\bot\gpt3\.venv\lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: 找不到指定的模块。

**Comment by RICHQAQ** [comment]
解决了，我是py3.9，应该有typing
重新安装了typing但还是没用（也许不用）
然后pip install msvc-runtime安装这个就好了
不知道是什么原因
